title: "Odd Security - Jacob Burenstam"
theme: "solarized" # black/white/league/sky/beige/simple/serif/blood/night/moon/solarized
# beige
transition: "page" # none/fade/slide/convex/concave/zoom/page
author: "Jacob Burenstam"
